insert into collectibles (name, image, campaign_id) values ('unavailable', 'http://dummyimage.com/146x100.png/ff4444/ffffff', 5);
insert into collectibles (name, image, campaign_id) values ('Grus antigone', 'http://dummyimage.com/228x100.png/cc0000/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Coendou prehensilis', 'http://dummyimage.com/215x100.png/cc0000/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Panthera leo persica', 'http://dummyimage.com/116x100.png/5fa2dd/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Sylvicapra grimma', 'http://dummyimage.com/148x100.png/ff4444/ffffff', 2);
insert into collectibles (name, image, campaign_id) values ('Neotis denhami', 'http://dummyimage.com/180x100.png/5fa2dd/ffffff', 2);
insert into collectibles (name, image, campaign_id) values ('Bubulcus ibis', 'http://dummyimage.com/151x100.png/cc0000/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Paroaria gularis', 'http://dummyimage.com/212x100.png/cc0000/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Bos frontalis', 'http://dummyimage.com/128x100.png/cc0000/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Lybius torquatus', 'http://dummyimage.com/131x100.png/ff4444/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Ploceus rubiginosus', 'http://dummyimage.com/250x100.png/5fa2dd/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Deroptyus accipitrinus', 'http://dummyimage.com/195x100.png/ff4444/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Meles meles', 'http://dummyimage.com/117x100.png/dddddd/000000', 2);
insert into collectibles (name, image, campaign_id) values ('Antilope cervicapra', 'http://dummyimage.com/122x100.png/5fa2dd/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Herpestes javanicus', 'http://dummyimage.com/154x100.png/dddddd/000000', 3);
insert into collectibles (name, image, campaign_id) values ('Cebus nigrivittatus', 'http://dummyimage.com/130x100.png/5fa2dd/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Cygnus buccinator', 'http://dummyimage.com/122x100.png/dddddd/000000', 4);
insert into collectibles (name, image, campaign_id) values ('Felis silvestris lybica', 'http://dummyimage.com/247x100.png/ff4444/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Lamprotornis superbus', 'http://dummyimage.com/219x100.png/5fa2dd/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Gyps bengalensis', 'http://dummyimage.com/191x100.png/dddddd/000000', 5);
insert into collectibles (name, image, campaign_id) values ('Coluber constrictor', 'http://dummyimage.com/220x100.png/5fa2dd/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Ephipplorhynchus senegalensis', 'http://dummyimage.com/233x100.png/dddddd/000000', 4);
insert into collectibles (name, image, campaign_id) values ('Gymnorhina tibicen', 'http://dummyimage.com/110x100.png/cc0000/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Tiliqua scincoides', 'http://dummyimage.com/188x100.png/cc0000/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Proteles cristatus', 'http://dummyimage.com/225x100.png/cc0000/ffffff', 5);
insert into collectibles (name, image, campaign_id) values ('Pelecanus occidentalis', 'http://dummyimage.com/126x100.png/dddddd/000000', 5);
insert into collectibles (name, image, campaign_id) values ('Tyto novaehollandiae', 'http://dummyimage.com/120x100.png/cc0000/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Macaca nemestrina', 'http://dummyimage.com/111x100.png/dddddd/000000', 3);
insert into collectibles (name, image, campaign_id) values ('Propithecus verreauxi', 'http://dummyimage.com/163x100.png/cc0000/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Cercopithecus aethiops', 'http://dummyimage.com/227x100.png/ff4444/ffffff', 2);
insert into collectibles (name, image, campaign_id) values ('Cabassous sp.', 'http://dummyimage.com/243x100.png/cc0000/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Canis lupus baileyi', 'http://dummyimage.com/197x100.png/5fa2dd/ffffff', 2);
insert into collectibles (name, image, campaign_id) values ('Papio cynocephalus', 'http://dummyimage.com/137x100.png/cc0000/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Paradoxurus hermaphroditus', 'http://dummyimage.com/190x100.png/ff4444/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Philetairus socius', 'http://dummyimage.com/190x100.png/dddddd/000000', 1);
insert into collectibles (name, image, campaign_id) values ('Kobus leche robertsi', 'http://dummyimage.com/130x100.png/dddddd/000000', 1);
insert into collectibles (name, image, campaign_id) values ('Melanerpes erythrocephalus', 'http://dummyimage.com/199x100.png/dddddd/000000', 4);
insert into collectibles (name, image, campaign_id) values ('Haematopus ater', 'http://dummyimage.com/161x100.png/ff4444/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Agouti paca', 'http://dummyimage.com/231x100.png/cc0000/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Eolophus roseicapillus', 'http://dummyimage.com/154x100.png/ff4444/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Francolinus coqui', 'http://dummyimage.com/217x100.png/dddddd/000000', 3);
insert into collectibles (name, image, campaign_id) values ('Phylurus milli', 'http://dummyimage.com/124x100.png/dddddd/000000', 5);
insert into collectibles (name, image, campaign_id) values ('Ateles paniscus', 'http://dummyimage.com/194x100.png/dddddd/000000', 5);
insert into collectibles (name, image, campaign_id) values ('Bucephala clangula', 'http://dummyimage.com/128x100.png/ff4444/ffffff', 5);
insert into collectibles (name, image, campaign_id) values ('Aonyx capensis', 'http://dummyimage.com/192x100.png/dddddd/000000', 4);
insert into collectibles (name, image, campaign_id) values ('Elephas maximus bengalensis', 'http://dummyimage.com/179x100.png/cc0000/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Lemur fulvus', 'http://dummyimage.com/181x100.png/dddddd/000000', 2);
insert into collectibles (name, image, campaign_id) values ('Drymarchon corias couperi', 'http://dummyimage.com/189x100.png/cc0000/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Redunca redunca', 'http://dummyimage.com/204x100.png/5fa2dd/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Hymenolaimus malacorhynchus', 'http://dummyimage.com/157x100.png/5fa2dd/ffffff', 2);
insert into collectibles (name, image, campaign_id) values ('Lutra canadensis', 'http://dummyimage.com/225x100.png/dddddd/000000', 4);
insert into collectibles (name, image, campaign_id) values ('Ramphastos tucanus', 'http://dummyimage.com/185x100.png/cc0000/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Pelecanus conspicillatus', 'http://dummyimage.com/144x100.png/dddddd/000000', 4);
insert into collectibles (name, image, campaign_id) values ('Callorhinus ursinus', 'http://dummyimage.com/189x100.png/dddddd/000000', 5);
insert into collectibles (name, image, campaign_id) values ('Creagrus furcatus', 'http://dummyimage.com/195x100.png/5fa2dd/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Fregata magnificans', 'http://dummyimage.com/119x100.png/5fa2dd/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Chlamydosaurus kingii', 'http://dummyimage.com/123x100.png/ff4444/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Sciurus vulgaris', 'http://dummyimage.com/213x100.png/ff4444/ffffff', 5);
insert into collectibles (name, image, campaign_id) values ('Recurvirostra avosetta', 'http://dummyimage.com/131x100.png/ff4444/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('unavailable', 'http://dummyimage.com/151x100.png/dddddd/000000', 5);
insert into collectibles (name, image, campaign_id) values ('Hystrix cristata', 'http://dummyimage.com/246x100.png/cc0000/ffffff', 5);
insert into collectibles (name, image, campaign_id) values ('Vanellus armatus', 'http://dummyimage.com/199x100.png/ff4444/ffffff', 5);
insert into collectibles (name, image, campaign_id) values ('Mycteria ibis', 'http://dummyimage.com/104x100.png/cc0000/ffffff', 2);
insert into collectibles (name, image, campaign_id) values ('Pelecans onocratalus', 'http://dummyimage.com/186x100.png/5fa2dd/ffffff', 5);
insert into collectibles (name, image, campaign_id) values ('Hymenolaimus malacorhynchus', 'http://dummyimage.com/113x100.png/dddddd/000000', 1);
insert into collectibles (name, image, campaign_id) values ('Mazama gouazoubira', 'http://dummyimage.com/208x100.png/cc0000/ffffff', 2);
insert into collectibles (name, image, campaign_id) values ('Aegypius occipitalis', 'http://dummyimage.com/107x100.png/cc0000/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Anas bahamensis', 'http://dummyimage.com/230x100.png/ff4444/ffffff', 2);
insert into collectibles (name, image, campaign_id) values ('Cervus canadensis', 'http://dummyimage.com/162x100.png/cc0000/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Carduelis uropygialis', 'http://dummyimage.com/239x100.png/cc0000/ffffff', 2);
insert into collectibles (name, image, campaign_id) values ('Cordylus giganteus', 'http://dummyimage.com/248x100.png/dddddd/000000', 3);
insert into collectibles (name, image, campaign_id) values ('Uraeginthus granatina', 'http://dummyimage.com/173x100.png/dddddd/000000', 4);
insert into collectibles (name, image, campaign_id) values ('Spheniscus magellanicus', 'http://dummyimage.com/122x100.png/5fa2dd/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Mazama gouazoubira', 'http://dummyimage.com/220x100.png/cc0000/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Catharacta skua', 'http://dummyimage.com/250x100.png/5fa2dd/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Pycnonotus barbatus', 'http://dummyimage.com/126x100.png/dddddd/000000', 3);
insert into collectibles (name, image, campaign_id) values ('Mirounga angustirostris', 'http://dummyimage.com/138x100.png/dddddd/000000', 2);
insert into collectibles (name, image, campaign_id) values ('Macropus robustus', 'http://dummyimage.com/125x100.png/cc0000/ffffff', 2);
insert into collectibles (name, image, campaign_id) values ('Balearica pavonina', 'http://dummyimage.com/192x100.png/5fa2dd/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('unavailable', 'http://dummyimage.com/164x100.png/5fa2dd/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Phascogale calura', 'http://dummyimage.com/204x100.png/5fa2dd/ffffff', 5);
insert into collectibles (name, image, campaign_id) values ('Gorilla gorilla', 'http://dummyimage.com/126x100.png/ff4444/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Cacatua tenuirostris', 'http://dummyimage.com/114x100.png/dddddd/000000', 5);
insert into collectibles (name, image, campaign_id) values ('Ploceus intermedius', 'http://dummyimage.com/236x100.png/dddddd/000000', 2);
insert into collectibles (name, image, campaign_id) values ('Tockus flavirostris', 'http://dummyimage.com/184x100.png/5fa2dd/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Loxodonta africana', 'http://dummyimage.com/240x100.png/5fa2dd/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Arctogalidia trivirgata', 'http://dummyimage.com/246x100.png/ff4444/ffffff', 2);
insert into collectibles (name, image, campaign_id) values ('Lepilemur rufescens', 'http://dummyimage.com/170x100.png/cc0000/ffffff', 3);
insert into collectibles (name, image, campaign_id) values ('Actophilornis africanus', 'http://dummyimage.com/142x100.png/5fa2dd/ffffff', 2);
insert into collectibles (name, image, campaign_id) values ('Agkistrodon piscivorus', 'http://dummyimage.com/141x100.png/ff4444/ffffff', 1);
insert into collectibles (name, image, campaign_id) values ('Aonyx capensis', 'http://dummyimage.com/150x100.png/dddddd/000000', 1);
insert into collectibles (name, image, campaign_id) values ('Pavo cristatus', 'http://dummyimage.com/119x100.png/ff4444/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Plegadis ridgwayi', 'http://dummyimage.com/224x100.png/dddddd/000000', 2);
insert into collectibles (name, image, campaign_id) values ('Merops bullockoides', 'http://dummyimage.com/236x100.png/ff4444/ffffff', 5);
insert into collectibles (name, image, campaign_id) values ('Pseudalopex gymnocercus', 'http://dummyimage.com/212x100.png/dddddd/000000', 3);
insert into collectibles (name, image, campaign_id) values ('Phalacrocorax albiventer', 'http://dummyimage.com/220x100.png/dddddd/000000', 5);
insert into collectibles (name, image, campaign_id) values ('unavailable', 'http://dummyimage.com/190x100.png/dddddd/000000', 1);
insert into collectibles (name, image, campaign_id) values ('Marmota caligata', 'http://dummyimage.com/221x100.png/cc0000/ffffff', 5);
insert into collectibles (name, image, campaign_id) values ('Phalaropus fulicarius', 'http://dummyimage.com/147x100.png/5fa2dd/ffffff', 4);
insert into collectibles (name, image, campaign_id) values ('Tauraco porphyrelophus', 'http://dummyimage.com/157x100.png/cc0000/ffffff', 2);
